export const GREET = 'greet'
export const INFORMATION = 'information'
export const OFFER = 'offer'
export const ANSWER = 'answer'
export const OUT = 'out'
export const DISCOVERY = 'discovery'
export const ROOMOFFER = 'roomOffer'
export const ROOMANSWER = 'roomAnswer'